name: dtogen
description: A command-line app which is used to generate DTOs and Entities from json
version: 1.0.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  code_builder: ^4.4.0
  dart_style: ^2.2.4
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  meta: ^1.7.0
  path: ^1.8.1

dev_dependencies:
  freezed: ^2.3.2
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.16.0
