name: dtogen_cli
description: A sample command-line application.
version: 0.1.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  args: ^2.3.1
  path: ^1.8.0
  dtogen:
    path: ../dtogen
  dtogen_shared:
    path: ../dtogen_shared

dev_dependencies:
  dtogen_lints:
    path: ../dtogen_lints
  test: ^1.16.0
