name: dtogen_shared
description: A sample command-line application.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=2.18.7 <3.0.0"

dependencies:
  bloc: ^8.1.0
  convenient_architecture: ^0.1.0+1
  dtogen:
    path: ../dtogen
  hive: ^2.2.3

dev_dependencies:
  dtogen_lints:
    path: ../dtogen_lints
  test: ^1.16.0
