name: dtogen_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  bloc: ^8.1.0
  copy_with_extension: ^5.0.0
  cupertino_icons: ^1.0.2
  dtogen:
    path: ../dtogen
  equatable: ^2.0.5
  flex_list: ^1.0.0
  fluent_ui: ^4.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.11
  system_theme: ^2.1.0
  toor: ^1.3.0

dev_dependencies:
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0
  dtogen_lints:
    path: ../dtogen_lints
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
