name: Deploy App To GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - ".github/**"
      - "packages/dtogen_app/**"

env:
  FLUTTER_VERSION: "3.7.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: packages/dtogen_app
